services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: micro
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    ports:
      - "1433:1433"
    volumes:
      - micro-data:/var/opt/mssql 
    networks:
      - backend-net
    restart: unless-stopped 

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend-app
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mssql
    networks:
      - backend-net
    restart: unless-stopped

volumes:
  micro-data:

networks:
  backend-net:
    driver: bridge
