# docker pull mcr.microsoft.com/mssql/server:2022-latest

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: micro
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    ports:
      - "1433:1433"
    volumes:
      - micro-data:/var/opt/mssql 
    restart: unless-stopped 


volumes:
  micro-data: